server:
  port: 8081

spring:
  application:
    name: finderai-chat-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/finderai_chat_backend_db
    username: postgres
    password:
  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true # true will show the sql in the log
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSXXX
    time-zone: UTC
  elasticsearch:
    uris: http://localhost:9200
    username:
    password:
    enabled: true

logging:
  level:
    root: DEBUG
    org.elasticsearch.client: DEBUG

ai:
  provider:
    finderai:
      api:
        url: "http://localhost:8080"
        key:
        model: finderaimodel
        limit: 5
    openai:
      api:
        url:
        key:
        model: 
        limit: 5
